# Generated by Django 2.1.2 on 2018-10-19 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('champion', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('img_url', models.CharField(max_length=255)),
                ('info_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_num', models.AutoField(primary_key=True, serialize=False)),
                ('season', models.PositiveIntegerField()),
                ('duration', models.DateTimeField()),
                ('team1', models.IntegerField()),
                ('team2', models.IntegerField()),
                ('date', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='UserGameData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kill', models.SmallIntegerField()),
                ('death', models.SmallIntegerField()),
                ('asist', models.SmallIntegerField()),
                ('cs', models.SmallIntegerField()),
                ('gold', models.PositiveIntegerField()),
                ('level', models.SmallIntegerField()),
                ('win', models.BooleanField()),
                ('team_num', models.SmallIntegerField()),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airgg.Champion')),
                ('game_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airgg.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('age', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=100)),
                ('preference_line', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('member', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='usergamedata',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airgg.Users'),
        ),
        migrations.AddField(
            model_name='ban',
            name='champion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airgg.Champion'),
        ),
        migrations.AddField(
            model_name='ban',
            name='game_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airgg.Game'),
        ),
    ]
