# Generated by Django 2.1.2 on 2018-10-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airgg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='duration',
            field=models.DurationField(),
        ),
    ]
