# Generated by Django 2.1.2 on 2018-10-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airgg', '0003_auto_20181019_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_num',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='ban',
            unique_together={('champion', 'game_num')},
        ),
    ]
