# Generated by Django 2.1.2 on 2018-11-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airgg', '0004_auto_20181019_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergamedata',
            name='line',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='usergamedata',
            unique_together={('user_id', 'game_num', 'champion')},
        ),
    ]
