# Generated by Django 2.1.2 on 2018-11-02 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airgg', '0005_auto_20181101_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='champion',
            name='img_url',
        ),
    ]
