# Generated by Django 2.1.2 on 2018-11-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airgg', '0006_remove_champion_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='position',
            field=models.CharField(default='member', max_length=100),
        ),
    ]
