# Generated by Django 2.1.2 on 2018-11-16 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airgg', '0007_users_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='duration',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
