# Generated by Django 2.1.2 on 2018-11-26 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airgg', '0008_auto_20181116_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='team1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='team2',
        ),
        migrations.RemoveField(
            model_name='usergamedata',
            name='team_num',
        ),
    ]
