# Generated by Django 2.1.2 on 2018-11-27 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airgg', '0009_auto_20181126_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('line', models.CharField(max_length=5, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='usergamedata',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airgg.Line'),
        ),
        migrations.AlterUniqueTogether(
            name='usergamedata',
            unique_together={('user_id', 'game_num', 'champion', 'line')},
        ),
    ]
