# Generated by Django 2.1.2 on 2018-11-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airgg', '0010_auto_20181127_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='line',
            field=models.CharField(default='UNKNOWN', max_length=5, primary_key=True, serialize=False),
        ),
    ]
