# Generated by Django 2.1.2 on 2018-12-06 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airgg', '0011_auto_20181127_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='age',
        ),
        migrations.RemoveField(
            model_name='users',
            name='location',
        ),
        migrations.RemoveField(
            model_name='users',
            name='name',
        ),
    ]
