export default {
  nowSeason: 4,
  homeBanner: '/static/airgg/img/alr_spring.jpg',
  tier: {
    unranked: '/static/airgg/img/tier/Iron_Emblem.png',
    bronze: '/static/airgg/img/tier/Bronze_Emblem.png',
    silver: '/static/airgg/img/tier/Silver_Emblem.png',
    gold: '/static/airgg/img/tier/Gold_Emblem.png',
    platinum: '/static/airgg/img/tier/Platinum_Emblem.png',
    diamond: '/static/airgg/img/tier/Diamond_Emblem.png',
    master: '/static/airgg/img/tier/Master_Emblem.png',
    challenger: '/static/airgg/img/tier/Challenger_Emblem.png',
  },
  lineImg: {
    TOP: '/static/airgg/img/Top_icon.png',
    JUG: '/static/airgg/img/Jungle_icon.png',
    MID: '/static/airgg/img/Mid_icon.png',
    BOT: '/static/airgg/img/Bot_icon.png',
    SUP: '/static/airgg/img/Support_icon.png',
  },
  menuList: [
    { title: '멤버', href: '/member' },
    { title: '랭킹', href: '/ranking' },
    { title: '통계', href: '/stats' },
    { title: '포지션 예측', href: '/position' },
    { title: '커뮤니티', href: 'https://cafe.naver.com/alightrest' },
    { title: '하나튜브', href: 'https://www.youtube.com/channel/UCGNbhTiN8xMGOKtiQbMxmkQ' },
  ],
  comments: {
    CARRY: '가장 높은 KDA 수치를 보유',
    MURDER: '내전에서 가장 높은 킬 수치를 보유',
    TERESA: '내전에서 가장 높은 어시스트 수치를 보유',
    JOINER: '내전  참가를 가장 많이한 사람',
    MOLA: '내전에서 가장 높은 데스 수치를 보유',
    THE_JUNGLE: '협곡 그 자체...',
  },
  lineComment: {
    TOP: 'The Top liner',
    JUG: 'The Jungle liner',
    MID: 'The Mid liner',
    BOT: 'The Bot liner',
    SUP: 'The Support Liner',
  },
};
